//! The encrypt command: checks, key, chunked encryption, verification from
//! disk, then the original is destroyed with the traces left of it, unless
//! kept, and a report printed.

use std::io::{self, IsTerminal};
use std::path::Path;
use std::time::Instant;

use crate::cli::Options;
use crate::error::{Error, Result};
use crate::explain::{self, Action};
use crate::files::{self, PartFile};
use crate::keys::{self, KeySource, Printed, UnusedKeyFile};
use crate::meta::Metadata;
use crate::report::{self, fmt_size};
use crate::term::{self, confirm, safe_path};
use crate::{KEY_LEN, desktop, history, protect, stream, wipe};

pub fn command(file: Option<&str>, options: &Options) -> Result<()> {
    let input = files::file_path("encrypt", file)?;
    files::input_len("encrypt", &input)?;
    let output = files::encrypted_path(&input);
    if output.exists() {
        return Err(Error::File(explain::output_exists(&output)));
    }
    // Problems found now save asking for a key that can't be used. Unless
    // it's to be kept, the original is opened to be overwritten too, which
    // fails now if that couldn't be done later.
    let mut original = wipe::Original::open(&input, !options.keep)?;
    files::check_writable(&output)?;
    if let Some(new_key) = &options.new_key {
        keys::check_new_key(new_key)?;
    }
    if let Some(filesystem) = files::copy_on_write(original.file()).filter(|_| !options.keep) {
        eprintln!("{}", explain::copy_on_write(&input, filesystem));
        if !options.yes && !confirm("Encrypt anyway?")? {
            eprintln!("Cancelled; nothing was encrypted.");
            return Ok(());
        }
    }

    let mut key_file = UnusedKeyFile::default();
    let (key, source) = keys::establish(&input, &mut key_file, options)?;
    let history = history::clean(Some(&key));

    if !options.yes && !confirm("Encrypt using AES-256-GCM?")? {
        eprintln!("Cancelled; nothing was encrypted.");
        return Ok(());
    }

    let started = Instant::now();
    let read_error = |e| Error::File(explain::file(Action::Read, &input, &e));
    let before = original.file().metadata().map_err(read_error)?;
    let len = before.len();
    // Captured before reading, which can update the access time.
    let metadata = Metadata::capture(original.file()).map_err(read_error)?;
    let meta_len = metadata.encoded_len();
    let mut encoded = files::secret_buffer(meta_len as u64)?;
    metadata.encode(&mut encoded);

    // A chunk at a time, so the file can be any size.
    let mut out = PartFile::create(&output, false)?;
    let mut progress = term::Progress::new("Encrypting", len);
    let sealed = stream::encrypt(
        &key,
        &encoded,
        &mut original.reader().map_err(read_error)?,
        len,
        &mut out,
        &mut |done| progress.update(done),
    )
    .map_err(|e| explain::stream_failure(e, &input, &output, None))?;
    drop(progress);
    out.finish()?;
    drop(encoded);

    // Prove the file on disk decrypts back to exactly what was read before the
    // original is touched.
    if let Err(e) = verify(&key, &output, len, &sealed.hash) {
        let _ = wipe::shred(&output);
        return Err(match e {
            Error::Interrupted => e,
            e => Error::File(format!(
                "{e}\nThe encrypted file didn't read back from disk as it was written, so it was \
                 removed and the original left untouched.\n{}",
                explain::DISK_TROUBLE
            )),
        });
    }
    drop(key);

    // Anything written to the original while it was read would be lost with
    // it, and the encrypted copy wouldn't match it either way.
    let after = original.file().metadata().map_err(read_error)?;
    if after.len() != len || after.modified().ok() != before.modified().ok() {
        let _ = wipe::shred(&output);
        return Err(Error::File(explain::changed_while_reading(&input)));
    }

    // Last chance to back out: past this point the original is destroyed.
    if protect::stop_requested() {
        let _ = wipe::shred(&output);
        return Err(Error::Interrupted);
    }
    key_file.keep();
    let (original_status, traces) = match options.keep {
        true => ("kept, as asked with --keep".into(), None),
        false => match original.destroy(&input) {
            Ok(status) => (status, desktop::forget(&input)),
            Err(warning) => (warning, None),
        },
    };
    let elapsed = started.elapsed();
    if options.quiet {
        return Ok(());
    }

    let mut rows = vec![("Cipher", "AES-256-GCM (authenticated encryption)".to_string())];
    match &source {
        KeySource::Generated { saved_to, printed } => {
            rows.push(("Key", "256-bit, generated by the OS CSPRNG".into()));
            rows.push(("Key storage", key_storage(saved_to.as_deref(), printed)));
        }
        KeySource::FromFile { path, .. } => {
            rows.push(("Key", format!("256-bit, from {}", safe_path(path))));
            rows.push(("Key storage", "your key file; not changed by this tool".into()));
        }
        KeySource::Entered => {
            rows.push(("Key", "256-bit, entered by you".into()));
            rows.push(("Key storage", "not stored by this tool".into()));
        }
    }
    let tags = sealed.chunks as usize * stream::TAG_LEN;
    let overhead = stream::HEADER_LEN + meta_len + tags;
    rows.extend([
        ("File key", "derived with HKDF-SHA256 from the key and a random 256-bit salt".into()),
        (
            "Chunks",
            format!("{} of up to 64 KiB, each with its own {}-bit auth tag", sealed.chunks, stream::TAG_LEN * 8),
        ),
        ("Input", format!("{}  {}", safe_path(&input), fmt_size(len as usize))),
        ("Output", format!("{}  {}", safe_path(&output), fmt_size(len as usize + overhead))),
        (
            "Overhead",
            format!(
                "{overhead} bytes ({} header + {meta_len} metadata + {tags} in tags)",
                stream::HEADER_LEN
            ),
        ),
        ("Metadata", format!("stored encrypted: {}", metadata.summary())),
        ("Integrity", "verified: re-read from disk, decrypted, SHA-256 matches original".into()),
        ("Original", original_status),
    ]);
    if let Some(traces) = traces {
        rows.push(("Desktop traces", traces));
    }
    rows.extend([
        ("Key and data", protect::memory_status().into()),
        ("Shell history", history),
        ("Time", format!("{elapsed:.2?}")),
    ]);
    let name = input.file_name().unwrap_or_default().to_string_lossy();
    let ask = io::stdin().is_terminal() && !options.yes;
    report::show("ENCRYPTION SUCCESSFUL", &rows, &format!("{name}.encryption-summary"), ask)
}

/// Where a generated key went, for the report.
fn key_storage(saved_to: Option<&Path>, printed: &Printed) -> String {
    match (saved_to, printed) {
        (Some(path), Printed::No) => format!("saved to {} (owner read/write only)", safe_path(path)),
        (Some(path), Printed::Erased) => {
            format!("saved to {} (owner read/write only); also shown once on screen", safe_path(path))
        }
        (Some(path), Printed::Captured(by)) => format!(
            "saved to {} (owner read/write only); also shown on screen and captured by {by}: anyone \
             with that copy can decrypt the file",
            safe_path(path)
        ),
        (None, Printed::Captured(by)) => {
            format!("shown on screen and captured by {by}: anyone with that copy can decrypt the file; not saved")
        }
        (None, _) => "shown once on screen, then erased; not saved".into(),
    }
}

/// Checks that the encrypted file decrypts back to the original contents, and
/// that its metadata reads back too, reading it a chunk at a time from the
/// disk rather than from memory.
fn verify(key: &[u8; KEY_LEN], path: &Path, len: u64, hash: &[u8; 32]) -> Result<()> {
    let read_error = |e| Error::File(explain::file(Action::Read, path, &e));
    let mut file = files::open_uncached(path).map_err(read_error)?;
    let body_len = file.metadata().map_err(read_error)?.len().saturating_sub(stream::HEADER_LEN as u64);
    let mut header = [0u8; stream::HEADER_LEN];
    std::io::Read::read_exact(&mut file, &mut header).map_err(read_error)?;
    let mut progress = term::Progress::new("Verifying", body_len);
    let opened = stream::decrypt(key, &header, &mut file, body_len, &mut std::io::sink(), &mut |done| {
        progress.update(done)
    })
    .map_err(|e| match e {
        stream::Error::Auth(n) => format!("verification failed: chunk {n} of the encrypted file didn't decrypt").into(),
        e => match explain::stream_failure(e, path, path, None) {
            Error::Interrupted => Error::Interrupted,
            e => format!("verification failed: {e}").into(),
        },
    })?;
    if opened.len != len || *opened.hash != *hash {
        return Err("verification failed: the encrypted file doesn't decrypt to the original".into());
    }
    Ok(())
}
